export const ID_SEPARATOR = "::";

export const gridTheme = {
  fontFamily: "Overpass, sans-serif",
  accentColor: "#0DBDFF",
  accentFg: "#ffb700",
  accentLight: "#0DBDFF",
  textDark: "#FFFFFF",
  textMedium: "#0DBDFF",
  textLight: "#FFFFFF",
  textBubble: "#ff0044",
  bgIconHeader: "#DDDDDD",
  fgIconHeader: "#81ff00",
  textHeader: "#DDDDDD",
  textGroupHeader: "#DDDDDD",
  textHeaderSelected: "#DDDDDD",
  bgCell: "#0F233E",
  bgCellMedium: "#0F233E",
  bgHeader: "#0F233E",
  bgHeaderHasFocus: "#17355D",
  bgHeaderHovered: "#17355D",
  bgBubble: "#81ff00",
  bgBubbleSelected: "#81ff00",
  bgSearchResult: "#434343",
  linkColor: "#ffb700",
  cellHorizontalPadding: 12,
  cellVerticalPadding: 0,
  headerFontStyle: "600 13px",
  baseFontStyle: "12px",
  lineHeight: 16,
};
